### ISSUE TITLE
Change of search engine

### ISSUE THREAD

**Issue by JaceThings** [simonerlic/Minimal-Startpage#2]
This is less of an issue and more of a question.

What would i have to change  `const search = 'https://duckduckgo.com/?t=ffab&q=';`  to, for it to search with chrome instead of DuckDuckGo?

If that even is what I would have to change of course.

**Comment by simonerlic** [comment]
Hey, sorry for taking a bit to respond! Assuming you want to use Google search instead of DuckDuckGo, you should change `'https://duckduckgo.com/?t=ffab&q='` to `'https://www.google.com/search?d&q='`. 

Basically, you want to copy the address that comes before what you searched for on Google, since that's what sets up the search query.

Hope that helps!
